#index:
#    path: /
#    controller: App\Controller\DefaultController::index

birghte:
  path: /brighte/delivery
  controller: App\DeliveryBundle\Controller\BrighteController::delivery

archistar:
  path: /archistar/property-analytics
  controller: App\PropertyAnalyticBundle\Controller\PropertyAnalyticController::getAnalyticsAction
