#index:
#    path: /
#    controller: App\Controller\DefaultController::index

birghte:
  path: /brighte/delivery
  controller: App\DeliveryBundle\Controller\BrighteController::delivery

#3rd Party Api
client_api:
  path: /clientUrl/
  controller: